Avoid implicit conversions, which are now flagged by gcc6
| api/qcoloroutput_p.h:74:60: error: shift expression '(1048575 << 20)' overflows [-fpermissive]
| api/qcoloroutput_p.h:74:63: error: enumerator value for 'BackgroundMask' is not an integer constant
|              BackgroundMask  = ((1 << BackgroundShift) - 1) << BackgroundShift

Upstream-Status: Inappropriate [Frozen upstream]
Signed-off-by: Khem Raj <raj.khem@gmail.com>